# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CadastreVersionViewer
                                 A QGIS plugin
 Query and view version history of Estonian cadastre units
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-26
        copyright            : (C) 2025 by Kaimar
        email                : -
        git sha              : $Format:%H$
 ***************************************************************************/

 Released under the MIT License. See the LICENSE file for details.
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CadastreVersionViewer class from file CadastreVersionViewer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cadastre_version_viewer import CadastreVersionViewer
    return CadastreVersionViewer(iface)
