# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CadastreVersionViewerDialog
                                 A QGIS plugin
 Query and view version history of Estonian cadastre units
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-26
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Kaimar
        email                : -
 ***************************************************************************/

 Released under the MIT License. See the LICENSE file for details.
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'cadastre_version_viewer_dialog_base.ui'))


class CadastreVersionViewerPanel(QtWidgets.QWidget, FORM_CLASS):
    """Panel widget that lives inside the QGIS dock (no longer a popup)."""

    def __init__(self, parent=None):
        """Constructor."""
        super(CadastreVersionViewerPanel, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>.
        self.setupUi(self)
