# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CadastreVersionViewer
                                 A QGIS plugin
 Query and view version history of Estonian cadastre units
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-03-26
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Kaimar
        email                : -
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.PyQt.QtWidgets import QTableWidgetItem
from PyQt5.QtCore import Qt
from qgis.core import (Qgis, QgsVectorLayer, QgsProject, QgsFillSymbol,
                       QgsCoordinateReferenceSystem, QgsCoordinateTransform)
from qgis.gui import QgsDockWidget
import json
import re
import urllib.parse
import urllib.request



# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the panel
from .cadastre_version_viewer_dialog import CadastreVersionViewerPanel
import os.path


class CadastreVersionViewer:
    """QGIS Plugin Implementation."""

    # A cadastre identifier looks like 78401:101:4011 (digits:digits:digits).
    TUNNUS_RE = re.compile(r"^\d+:\d+:\d+$")
    # Maa- ja Ruumiamet address search (gazetteer) service.
    GAZETTEER_URL = "https://aks.geoportaal.ee/inaks/inaadress/gazetteer"
    # The gazetteer rejects the default urllib user agent with HTTP 403.
    HTTP_HEADERS = {
        "User-Agent": "QGIS CadastreVersionViewer",
        "Referer": "https://aks.geoportaal.ee/inaks/inaadress",
    }
    # Outline colors cycled over the version layers loaded into one group.
    VERSION_COLORS = ["#e41a1c", "#377eb8", "#4daf4a", "#984ea3",
                      "#ff7f00", "#a65628"]

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'CadastreVersionViewer_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Kataster')
        # Dock widget and its inner panel (created lazily in run())
        self.dock = None
        self.panel = None

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('CadastreVersionViewer', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToWebMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        # Load the icon straight from the file on disk (not the compiled
        # resources.py), so replacing icon.png takes effect on the next reload.
        icon_path = os.path.join(self.plugin_dir, 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Kataster'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        if self.dock is not None:
            self.iface.removeDockWidget(self.dock)
            self.dock.deleteLater()
            self.dock = None
            self.panel = None
        for action in self.actions:
            self.iface.removePluginWebMenu(
                self.tr(u'&Kataster'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Show (or toggle) the dock panel that does all the real work."""

        # Create the dock + panel only once, then reuse it on later clicks.
        if self.dock is None:
            self.panel = CadastreVersionViewerPanel()
            self.panel.searchButton.clicked.connect(self.search_versions)
            self.panel.loadButton.clicked.connect(self.load_selected_versions)
            self.panel.selectAllButton.clicked.connect(self.toggle_select_all)
            # Pressing Enter in the search field triggers the search.
            self.panel.tunnusInput.returnPressed.connect(self.search_versions)
            # Double-clicking a version row loads just that version;
            # the checkboxes + button remain for loading several at once.
            self.panel.versionTable.cellDoubleClicked.connect(self.load_version_row)
            # Picking a different cadastre unit from an address match reloads it.
            self.panel.addressCombo.activated.connect(self.on_address_match_selected)
            self.hide_address_matches()

            self.panel.versionTable.setColumnCount(3)  # vali, kehtiv_alates, kehtiv_kuni
            self.panel.versionTable.setHorizontalHeaderLabels(
                ["Vali", "Kehtiv alates", "Kehtiv kuni"])
            self.panel.versionTable.horizontalHeader().setStretchLastSection(True)

            # Read-only key/value table for border-point ("piiripunkt") results.
            self.panel.pointTable.setColumnCount(2)
            self.panel.pointTable.setHorizontalHeaderLabels(["Atribuut", "Väärtus"])
            self.panel.pointTable.horizontalHeader().setStretchLastSection(True)
            self.panel.pointTable.verticalHeader().setVisible(False)
            self.panel.pointTable.setEditTriggers(
                self.panel.pointTable.NoEditTriggers)

            self.dock = QgsDockWidget(self.tr(u'Kataster'),
                                      self.iface.mainWindow())
            self.dock.setObjectName("CadastreVersionViewerDock")
            self.dock.setWidget(self.panel)
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dock)

        # Toggle visibility so the toolbar button shows/hides the panel.
        self.dock.setUserVisible(not self.dock.isUserVisible())
        if self.dock.isUserVisible():
            self.panel.tunnusInput.setFocus()





    def search_versions(self):
        """Dispatch on the search box: cadastre tunnus, border point, or address."""
        query = self.panel.tunnusInput.text().strip()
        if not query:
            self.iface.messageBar().pushMessage(
                self.tr(u'Kataster'),
                self.tr(u'Sisesta katastritunnus, aadress või piiripunkti number.'),
                level=Qgis.Info, duration=4)
            return

        # A new search clears any leftover address-match dropdown.
        self.hide_address_matches()

        if self.TUNNUS_RE.match(query):
            # Looks like a tunnus -> query versions straight away.
            self.set_results_mode("versions")
            self.load_versions_for_tunnus(query)
        elif query.isdigit():
            # All digits -> a border point (piiripunkti_nr).
            self.search_border_point(query)
        else:
            # Treat it as an address -> resolve to cadastre unit(s) first.
            self.set_results_mode("versions")
            self.search_by_address(query)

    def search_by_address(self, text):
        """Resolve an address to cadastre unit(s) via the gazetteer service."""
        matches = self.resolve_address(text)
        if matches is None:
            return  # network/parse error already reported

        if not matches:
            self.iface.messageBar().pushMessage(
                self.tr(u'Kataster'),
                self.tr(u'Aadressile "{}" ei leitud katastriüksust.').format(text),
                level=Qgis.Warning, duration=5)
            return

        if len(matches) == 1:
            tunnus, label = matches[0]
            self.iface.messageBar().pushMessage(
                self.tr(u'Kataster'),
                self.tr(u'Aadress lahendati: {} ({}).').format(label, tunnus),
                level=Qgis.Info, duration=4)
            self.load_versions_for_tunnus(tunnus)
            return

        # Several cadastre units match -> let the user pick, load the first now.
        self.show_address_matches(matches)
        self.load_versions_for_tunnus(matches[0][0])

    def resolve_address(self, text):
        """Return a de-duplicated list of (tunnus, label) cadastre matches.

        Returns an empty list when nothing matched, or None on error (the
        error is reported to the message bar before returning).
        """
        params = urllib.parse.urlencode({
            "address": text,
            "features": "KATASTRIYKSUS",  # only cadastre units
            "results": 20,
            "ky": 1,                      # include pending ("ootel") units
            "appartment": 0,
        })
        url = "{}?{}".format(self.GAZETTEER_URL, params)

        self.panel.setCursor(Qt.WaitCursor)
        try:
            req = urllib.request.Request(url, headers=self.HTTP_HEADERS)
            with urllib.request.urlopen(req) as response:
                raw = response.read().decode("utf-8")
        except Exception as e:
            self.iface.messageBar().pushMessage(
                self.tr(u'Kataster'),
                self.tr(u'Aadressiotsing ebaõnnestus: {}').format(e),
                level=Qgis.Critical, duration=6)
            return None
        finally:
            self.panel.unsetCursor()

        # The gazetteer is documented as JSONP; strip a callback(...) wrapper
        # if present, otherwise parse the plain JSON object directly.
        try:
            stripped = raw.strip()
            if not stripped.startswith("{"):
                stripped = stripped[stripped.find("{"):stripped.rfind("}") + 1]
            data = json.loads(stripped)
        except Exception:
            self.iface.messageBar().pushMessage(
                self.tr(u'Kataster'),
                self.tr(u'Aadressivastust ei õnnestunud lugeda.'),
                level=Qgis.Critical, duration=6)
            return None

        matches = []
        seen = set()
        for obj in data.get("addresses", []):
            tunnus = obj.get("tunnus")
            if not tunnus or tunnus in seen:
                continue
            if not self.TUNNUS_RE.match(tunnus):
                continue  # keep only genuine cadastre identifiers
            seen.add(tunnus)
            label = (obj.get("taisaadress") or obj.get("pikkaadress")
                     or obj.get("aadresstekst") or tunnus)
            matches.append((tunnus, label))
        return matches

    def show_address_matches(self, matches):
        """Show the dropdown of cadastre units found for an ambiguous address."""
        combo = self.panel.addressCombo
        combo.blockSignals(True)
        combo.clear()
        for tunnus, label in matches:
            combo.addItem(u"{} — {}".format(label, tunnus), tunnus)
        combo.setCurrentIndex(0)
        combo.blockSignals(False)
        self.panel.matchLabel.setVisible(True)
        combo.setVisible(True)

    def hide_address_matches(self):
        """Hide and clear the address-match dropdown."""
        self.panel.matchLabel.setVisible(False)
        self.panel.addressCombo.setVisible(False)
        self.panel.addressCombo.clear()

    def on_address_match_selected(self, index):
        """User picked a different cadastre unit from the address matches."""
        tunnus = self.panel.addressCombo.itemData(index)
        if tunnus:
            self.load_versions_for_tunnus(tunnus)

    def load_versions_for_tunnus(self, tunnus):
        # Encode the CQL filter manually
        encoded_tunnus = urllib.parse.quote(f"'{tunnus}'")
        base_url = (
            "https://gsavalik.envir.ee/geoserver/kataster/wfs"
            "?service=WFS"
            "&version=1.0.0"
            "&request=GetFeature"
            "&typeName=kataster:ky_versioonid"
            "&outputFormat=application/json"
            f"&CQL_FILTER=tunnus={encoded_tunnus}"
        )

        # Show a busy cursor while the (blocking) network request runs.
        self.panel.setCursor(Qt.WaitCursor)
        try:
            req = urllib.request.Request(base_url, headers=self.HTTP_HEADERS)
            with urllib.request.urlopen(req) as response:
                geojson = response.read().decode("utf-8")
        except Exception as e:
            self.iface.messageBar().pushMessage(
                self.tr(u'Kataster'),
                self.tr(u'Andmete pärimine ebaõnnestus: {}').format(e),
                level=Qgis.Critical, duration=6)
            return
        finally:
            self.panel.unsetCursor()

        # Load it into QGIS as a temporary layer
        vlayer = QgsVectorLayer(geojson, "Cadastre Versions", "ogr")
        if not vlayer.isValid():
            self.iface.messageBar().pushMessage(
                self.tr(u'Kataster'),
                self.tr(u'Vastust ei õnnestunud lugeda.'),
                level=Qgis.Critical, duration=6)
            return

        features = list(vlayer.getFeatures())
        self.panel.versionTable.clearContents()
        self.panel.versionTable.setRowCount(len(features))

        if not features:
            self.iface.messageBar().pushMessage(
                self.tr(u'Kataster'),
                self.tr(u'Tunnusele "{}" versioone ei leitud.').format(tunnus),
                level=Qgis.Warning, duration=5)
            return

        def format_qdatetime(value):
            if hasattr(value, "toString"):
                return value.toString("yyyy-MM-dd")
            return str(value)


        for row_idx, feat in enumerate(features):
            checkbox_item = QTableWidgetItem()
            checkbox_item.setFlags(Qt.ItemIsEnabled | Qt.ItemIsUserCheckable)
            checkbox_item.setCheckState(Qt.Unchecked)
            self.panel.versionTable.setItem(row_idx, 0, checkbox_item)

            # Format the QDateTime nicely for the user
            self.panel.versionTable.setItem(row_idx, 1, QTableWidgetItem(format_qdatetime(feat["kehtiv_alates"])))
            self.panel.versionTable.setItem(row_idx, 2, QTableWidgetItem(format_qdatetime(feat["kehtiv_kuni"])))

            self.panel.versionTable.item(row_idx, 0).setData(Qt.UserRole, feat)

        # Show the user where the unit is without loading any layer yet.
        self.flash_versions_on_map(features)

        self.iface.messageBar().pushMessage(
            self.tr(u'Kataster'),
            self.tr(u'Leiti {} versiooni.').format(len(features)),
            level=Qgis.Success, duration=4)

    def flash_versions_on_map(self, features):
        """Zoom the canvas to the unit and briefly flash its outline(s)."""
        geoms = [f.geometry() for f in features if f.hasGeometry()]
        if not geoms:
            return
        crs = QgsCoordinateReferenceSystem("EPSG:3301")
        canvas = self.iface.mapCanvas()

        extent = geoms[0].boundingBox()
        for g in geoms[1:]:
            extent.combineExtentWith(g.boundingBox())
        try:
            xform = QgsCoordinateTransform(
                crs, canvas.mapSettings().destinationCrs(), QgsProject.instance())
            extent = xform.transformBoundingBox(extent)
        except Exception:
            pass  # canvas CRS == 3301 or transform failed; use as-is
        extent.scale(1.3)
        canvas.setExtent(extent)
        canvas.refresh()

        try:
            # flashes defaults to 3; one clear blink is enough.
            canvas.flashGeometries(geoms, crs, flashes=1, duration=600)
        except Exception:
            pass  # flashing is a nicety; zooming already happened





    # ------------------------------------------------------------------
    # Border point (piiripunkt) search
    # ------------------------------------------------------------------

    def set_results_mode(self, mode):
        """Switch the panel between version results and border-point results."""
        is_point = (mode == "point")
        self.panel.versionTable.setVisible(not is_point)
        self.panel.selectAllButton.setVisible(not is_point)
        self.panel.loadButton.setVisible(not is_point)
        self.panel.pointTable.setVisible(is_point)

    def search_border_point(self, nr):
        """Look up a border point by piiripunkti_nr, show it on the map and list
        its attributes."""
        base_url = (
            "https://gsavalik.envir.ee/geoserver/kataster/wfs"
            "?service=WFS"
            "&version=1.0.0"
            "&request=GetFeature"
            "&typeName=kataster:ky_punktid_kehtiv"
            "&outputFormat=application/json"
            "&CQL_FILTER=piiripunkti_nr=" + urllib.parse.quote(str(nr))
        )

        self.panel.setCursor(Qt.WaitCursor)
        try:
            req = urllib.request.Request(base_url, headers=self.HTTP_HEADERS)
            with urllib.request.urlopen(req) as response:
                geojson = response.read().decode("utf-8")
        except Exception as e:
            self.iface.messageBar().pushMessage(
                self.tr(u'Kataster'),
                self.tr(u'Piiripunkti otsing ebaõnnestus: {}').format(e),
                level=Qgis.Critical, duration=6)
            return
        finally:
            self.panel.unsetCursor()

        try:
            data = json.loads(geojson)
        except Exception:
            self.iface.messageBar().pushMessage(
                self.tr(u'Kataster'),
                self.tr(u'Vastust ei õnnestunud lugeda.'),
                level=Qgis.Critical, duration=6)
            return

        features = data.get("features", [])
        if not features:
            self.iface.messageBar().pushMessage(
                self.tr(u'Kataster'),
                self.tr(u'Piiripunkti nr "{}" ei leitud.').format(nr),
                level=Qgis.Warning, duration=5)
            return

        # A border point is shared between neighbouring units, so several
        # features can come back for the same physical point.
        self.set_results_mode("point")
        self.display_point_attributes([f.get("properties", {}) for f in features])
        self.show_point_on_map(geojson, nr)
        self.iface.messageBar().pushMessage(
            self.tr(u'Kataster'),
            self.tr(u'Piiripunkt {} leitud.').format(nr),
            level=Qgis.Success, duration=4)

    def display_point_attributes(self, props_list):
        """Fill the key/value table with the border point's attributes."""
        first = props_list[0]
        tunnused = u", ".join(sorted({
            str(p.get("tunnus")) for p in props_list if p.get("tunnus")}))

        rows = [
            (self.tr(u'Piiripunkti nr'), first.get("piiripunkti_nr")),
            (self.tr(u'Katastritunnus(ed)'), tunnused),
            (self.tr(u'X'), first.get("x")),
            (self.tr(u'Y'), first.get("y")),
            (self.tr(u'Piiripunkt'), first.get("piiripunkt")),
            (self.tr(u'Mõõtmise aeg'), self.format_date(first.get("punkt_moot_aeg"))),
            (self.tr(u'Mõõtmisviis'), first.get("mootviis")),
            (self.tr(u'Mõõtja'), first.get("mootja")),
            (self.tr(u'Vajadus asukoht selgitada'),
             self.format_bool(first.get("vajadus_asukoht_selgitada"))),
        ]

        table = self.panel.pointTable
        table.clearContents()
        table.setRowCount(len(rows))
        for row_idx, (key, value) in enumerate(rows):
            table.setItem(row_idx, 0, QTableWidgetItem(str(key)))
            text = "" if value is None else str(value)
            table.setItem(row_idx, 1, QTableWidgetItem(text))
        table.resizeColumnToContents(0)

    def show_point_on_map(self, geojson, nr):
        """Add the border point as a layer and zoom the map canvas to it."""
        layer = QgsVectorLayer(geojson, u"Piiripunkt {}".format(nr), "ogr")
        if not layer.isValid():
            return  # attributes are already shown; the map is best-effort
        QgsProject.instance().addMapLayer(layer, False)
        self.get_layer_group(self.tr(u'Piiripunktid')).insertLayer(0, layer)
        try:
            canvas = self.iface.mapCanvas()
            layer.selectAll()
            canvas.zoomToSelected(layer)
            layer.removeSelection()
            canvas.zoomScale(1000)  # a single point needs a sensible scale
            canvas.refresh()
        except Exception:
            pass

    @staticmethod
    def format_bool(value):
        if value is True:
            return "Jah"
        if value is False:
            return "Ei"
        return ""

    @staticmethod
    def format_date(value):
        # WFS dates arrive like "2003-06-11Z"; drop the trailing marker.
        if isinstance(value, str) and value.endswith("Z"):
            return value[:-1]
        return "" if value is None else str(value)

    def toggle_select_all(self):
        """Check all rows, or uncheck them if they are already all checked."""
        table = self.panel.versionTable
        rows = range(table.rowCount())
        all_checked = rows and all(
            table.item(r, 0).checkState() == Qt.Checked for r in rows)
        new_state = Qt.Unchecked if all_checked else Qt.Checked
        for r in rows:
            table.item(r, 0).setCheckState(new_state)

    def load_selected_versions(self):
        table = self.panel.versionTable
        selected_features = []

        for row in range(table.rowCount()):
            item = table.item(row, 0)
            if item.checkState() == Qt.Checked:
                feature = item.data(Qt.UserRole)
                selected_features.append(feature)

        if not selected_features:
            self.iface.messageBar().pushMessage(
                self.tr(u'Kataster'),
                self.tr(u'Vali vähemalt üks versioon.'),
                level=Qgis.Info, duration=4)
            return

        for feat in selected_features:
            self.add_version_layer(feat)

    def load_version_row(self, row, column):
        """Double-click on a table row loads just that version."""
        item = self.panel.versionTable.item(row, 0)
        feat = item.data(Qt.UserRole) if item else None
        if feat is not None:
            self.add_version_layer(feat)

    def get_layer_group(self, name):
        """Find or create a top-level layer-tree group with the given name."""
        root = QgsProject.instance().layerTreeRoot()
        group = root.findGroup(name)
        if group is None:
            group = root.insertGroup(0, name)
        return group

    def add_version_layer(self, feat):
        """Add one cadastre version as a styled memory layer, grouped by tunnus."""
        date = feat["kehtiv_alates"]
        if hasattr(date, "toString"):
            date_text = date.toString("yyyy-MM-dd")
        else:
            date_text = str(date)

        # Create memory layer holding the single version feature
        layer = QgsVectorLayer("Polygon?crs=EPSG:3301",
                               f"Versioon {date_text}", "memory")
        layer.dataProvider().addAttributes(feat.fields().toList())
        layer.updateFields()
        layer.startEditing()
        layer.addFeature(feat)
        layer.commitChanges()

        # One layer-tree group per cadastre unit keeps the Layers panel tidy.
        try:
            group_name = str(feat["tunnus"])
        except Exception:
            group_name = self.panel.tunnusInput.text().strip()
        group = self.get_layer_group(group_name)

        # Transparent fill + colored outline so stacked versions stay readable;
        # the color cycles with each layer already in the group.
        color = self.VERSION_COLORS[len(group.children()) % len(self.VERSION_COLORS)]
        symbol = QgsFillSymbol.createSimple({
            "color": "0,0,0,0",
            "outline_color": color,
            "outline_width": "0.8",
        })
        layer.renderer().setSymbol(symbol)
        layer.triggerRepaint()

        QgsProject.instance().addMapLayer(layer, False)
        group.insertLayer(0, layer)


